{{- if .Values.elasticsearch.createCert }}
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: {{ template "elasticsearch.name" . }}-certificates
  labels:
    app: {{ template "elasticsearch.name" . }}
    chart: "{{ .Chart.Name }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
data:
{{ ( include "elasticsearch.gen-certs" . ) | indent 2 }}
{{- end }}