{{- range $inCluster_key, $inCluster_value := .Values.inClusterCredentials }}
apiVersion: v1
kind: Secret
metadata:
  name: incluster-credential-secret                  
  namespace: {{ $.Release.Namespace }}
  annotations:
    {{- with $inCluster_value.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
    argocd.argoproj.io/secret-type: cluster
    {{- with $inCluster_value.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
type: Opaque
stringData:
  name:  "{{ $inCluster_key }}"                                                                      
  server: "https://kubernetes.default.svc"                                                                    
  config: |
    {"tlsClientConfig":{"insecure":false}}
{{- end }}
